/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;
    import logic.persegiPanjang;
/**
 *
 * @author Salsadila
 */
public class persegiPanjangView extends javax.swing.JFrame {
    persegiPanjang control;
    /**
     * Creates new form persegiPanjangView
     */
    
    public persegiPanjangView() {
        initComponents();
        control = new persegiPanjang();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtpanjang = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        label_keliling = new javax.swing.JLabel();
        txtlebar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        kelilingg = new javax.swing.JLabel();
        luass = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();

        jLabel2.setIcon(new javax.swing.ImageIcon("E:\\pic\\0fb9e438bf292df2141c58fe0751ebd1.jpg")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Penjang");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 70, 50, 30);
        getContentPane().add(txtpanjang);
        txtpanjang.setBounds(80, 70, 160, 30);

        jButton1.setText("Hitung");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(260, 110, 100, 30);
        getContentPane().add(label_keliling);
        label_keliling.setBounds(80, 200, 0, 30);

        txtlebar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlebarActionPerformed(evt);
            }
        });
        getContentPane().add(txtlebar);
        txtlebar.setBounds(80, 110, 160, 30);

        jLabel3.setText("Keliling : ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 200, 60, 30);

        jLabel4.setText("Lebar");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 110, 50, 30);

        jLabel5.setText("Luas : ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 160, 50, 30);

        kelilingg.setText("0");
        getContentPane().add(kelilingg);
        kelilingg.setBounds(100, 200, 32, 30);

        luass.setText("0");
        getContentPane().add(luass);
        luass.setBounds(100, 160, 32, 30);

        jButton2.setText("Kembali");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(260, 250, 100, 30);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 240, 400, 20);

        jLabel6.setIcon(new javax.swing.ImageIcon("E:\\pic\\0fb9e438bf292df2141c58fe0751ebd1.jpg")); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(-200, -120, 650, 450);

        setBounds(0, 0, 416, 339);
    }// </editor-fold>//GEN-END:initComponents

    private void txtlebarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlebarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlebarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        double luas=0;
        double keliling=0;
        double panjang=Double.parseDouble(txtpanjang.getText());
        double lebar = Double.parseDouble(txtlebar.getText());
        control.setPanjang(panjang);
        control.setLebar(lebar);
        luas=control.hitungLuas();
        keliling = control.hitungKeliling();
 
        luass.setText(String.valueOf(luas));
        kelilingg.setText(String.valueOf(keliling));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new mainView().show();
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(persegiPanjangView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(persegiPanjangView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(persegiPanjangView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(persegiPanjangView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new persegiPanjangView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel kelilingg;
    private javax.swing.JLabel label_keliling;
    private javax.swing.JLabel luass;
    private javax.swing.JTextField txtlebar;
    private javax.swing.JTextField txtpanjang;
    // End of variables declaration//GEN-END:variables
}
