/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;
    import logic.segitiga;
/**
 *
 * @author Salsadila
 */
public class segitigaView extends javax.swing.JFrame {
    segitiga control;
    /**
     * Creates new form segitigaView
     */
    public segitigaView() {
        initComponents();
        control = new segitiga();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        txtsisi2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txttinggi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        label_luas = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtsisi3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtalas = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtsisi1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        luass = new javax.swing.JLabel();
        kelilingg = new javax.swing.JLabel();
        label_keliling = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();

        jButton3.setText("Kembali");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 310, 400, 20);

        jLabel1.setText("Sisi 2");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 200, 50, 30);

        txtsisi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsisi2ActionPerformed(evt);
            }
        });
        getContentPane().add(txtsisi2);
        txtsisi2.setBounds(80, 200, 160, 30);

        jButton1.setText("Hitung Keliling");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(250, 240, 130, 30);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 110, 0, 30);
        getContentPane().add(txttinggi);
        txttinggi.setBounds(80, 70, 160, 30);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 110, 0, 30);

        jLabel4.setText("Tinggi");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 70, 50, 30);
        getContentPane().add(label_luas);
        label_luas.setBounds(80, 110, 0, 30);

        jLabel6.setText("Sisi 3");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 240, 50, 30);

        txtsisi3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsisi3ActionPerformed(evt);
            }
        });
        getContentPane().add(txtsisi3);
        txtsisi3.setBounds(80, 240, 160, 30);

        jLabel7.setText("Alas");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 30, 50, 30);

        txtalas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtalasActionPerformed(evt);
            }
        });
        getContentPane().add(txtalas);
        txtalas.setBounds(80, 30, 160, 30);

        jLabel8.setText("Sisi 1");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 160, 50, 30);

        txtsisi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsisi1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtsisi1);
        txtsisi1.setBounds(80, 160, 160, 30);

        jButton2.setText("Hitung Luas");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(250, 70, 130, 30);

        luass.setText("0");
        getContentPane().add(luass);
        luass.setBounds(90, 110, 30, 30);

        kelilingg.setText("0");
        getContentPane().add(kelilingg);
        kelilingg.setBounds(100, 280, 50, 30);
        getContentPane().add(label_keliling);
        label_keliling.setBounds(80, 280, 0, 30);

        jLabel11.setText("Luas :");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(30, 110, 50, 30);

        jLabel12.setText("Keliling :");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(30, 280, 50, 30);

        jButton4.setText("Kembali");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(310, 320, 80, 30);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(0, 150, 400, 2);

        jLabel5.setIcon(new javax.swing.ImageIcon("E:\\pic\\0fb9e438bf292df2141c58fe0751ebd1.jpg")); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(-280, 0, 810, 620);

        setBounds(0, 0, 416, 400);
    }// </editor-fold>//GEN-END:initComponents

    private void txtsisi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsisi2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsisi2ActionPerformed

    private void txtsisi3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsisi3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsisi3ActionPerformed

    private void txtalasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtalasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtalasActionPerformed

    private void txtsisi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsisi1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsisi1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        double keliling = 0;
 
        double sisi1 = Double.parseDouble(txtsisi1.getText());
        double sisi2 = Double.parseDouble(txtsisi2.getText());
        double sisi3 = Double.parseDouble(txtsisi3.getText());
        control.setSisi1(sisi1);
        control.setSisi2(sisi2);
        control.setSisi3(sisi3);
        keliling = control.hitungKeliling();
        kelilingg.setText(String.valueOf(keliling));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        double luas = 0;
        double alas = Double.parseDouble(txtalas.getText());
        double tinggi = Double.parseDouble(txttinggi.getText());
        control.setAlas(alas);
        control.setTinggi(tinggi);
        luas = control.hitungLuas();
        luass.setText(String.valueOf(luas));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new mainView().show();
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        new mainView().show();
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(segitigaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(segitigaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(segitigaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(segitigaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new segitigaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel kelilingg;
    private javax.swing.JLabel label_keliling;
    private javax.swing.JLabel label_luas;
    private javax.swing.JLabel luass;
    private javax.swing.JTextField txtalas;
    private javax.swing.JTextField txtsisi1;
    private javax.swing.JTextField txtsisi2;
    private javax.swing.JTextField txtsisi3;
    private javax.swing.JTextField txttinggi;
    // End of variables declaration//GEN-END:variables
}
